<?php $isMasterpassEnabled = Mage::helper('masterpass')->isMasterpassEnabled(); ?>
<?php if ($isMasterpassEnabled): ?>
    <?php
    $prefix = '';
    if (Mage::getStoreConfig('masterpass/config/environment') === 'sandbox') {
        $prefix .= Mage::getStoreConfig('masterpass/config/environment') . ".";
    }
    ?>

    <script type="text/javascript" src="https://<?php echo $prefix; ?>masterpass.com/lightbox/Switch/integration/MasterPass.client.js"></script>
    <?php if (!Mage::helper('masterpass')->isExpressEnabled()) { ?>
        <div class="page-title">
            <h2>FOR FASTER CHECKOUT</h2>
            <a class="pair-mp-wallet" href="#" onclick="handleBuyWithMasterPass()" title="Buy With MasterPass"><img src="https://www.mastercard.com/mc_us/wallet/img/mcpp_wllt_btn_chk_<?php echo Mage::getStoreConfig('masterpass/config/buttonsize'); ?>.png"/></a>
        </div>
        <?php if (Mage::getStoreConfig('masterpass/config/enabledlearnmore')): ?>
            <?php echo Mage::getStoreConfig('masterpass/config/learnmoremasterpasslink'); ?>
        <?php endif ?>
        <div style="margin: 25px 0 10px;">- OR -</div>
        <script type="text/javascript">
                    //<![CDATA[
                            function handleBuyWithMasterPass() {
                            new Ajax.Request('<?php echo $this->getUrl() . 'masterpass/index/validatePk'; ?>',
                            {
                            method:'get',
                                    onSuccess: function(transport){
                                    var response = transport.responseText;
                                            if (response != ''){
        <?php $data = $this->helper('masterpass')->getMerchantSettings(); ?>
                                    var token = "<?php print_r($this->helper('masterpass')->postShoppingCart()); ?>";
                                            if (token != ''){
                                    MasterPass.client.checkout({
                                    "requestToken":token,
        <?php if (Mage::getStoreConfig('masterpass/config/callbackurl') != '') { ?>
                                        "callbackUrl":"<?php echo Mage::getStoreConfig('masterpass/config/callbackurl'); ?>",
        <?php } else { ?>
                                        "callbackUrl":"<?php echo $this->getUrl() . 'masterpass/index/callback'; ?>",
        <?php } ?>
                                    "merchantCheckoutId":"<?php echo $data['checkout_id']; ?>",
                                            "allowedCardTypes":"<?php print_r($this->helper('masterpass')->acceptedCards()); ?>",
                                            "cancelCallback" : "<?php echo $this->getUrl(); ?>",
                                            "suppressShippingAddressEnable": "<?php echo $data['suppressShipping']; ?>",
                                            "loyaltyEnabled" : "<?php echo $data['loyaltyEnabled']; ?>",
        <?php if ($data['loyaltyEnabled'] == 'true') { ?>
                                        "allowedLoyaltyPrograms" : "<?php echo $data['loyaltyProgram']; ?>",
        <?php } ?>
                                    "requestBasicCheckout" : "<?php echo $data['requestBasicCheckout']; ?>",
                                            "version":"<?php echo $data['version']; ?>"
                                    });
                                    } else{
                                    window.location.href = '<?php echo Mage::getUrl('', array('_secure' => true)); ?>masterpass/index/callback';
                                    }

                                    } else{
                                    location.reload();
                                    }
                                    } });
                            }
                    //]]>
        </script>

    <?php } elseif (Mage::getSingleton('customer/session')->isLoggedIn()) { ?>
        <div class="page-title">
            <h2>FOR FASTER CHECKOUT</h2>
            <a class="pair-mp-wallet" href="#" onclick="<?php if ($this->walletIsPaired()): ?> window.location = '<?php echo Mage::getUrl('', array('_secure' => true)) . "masterpass/masterpasspairing/precheckout"; ?>';<?php else: ?>pairWithMasterPass()<?php endif; ?>"><img src="https://www.mastercard.com/mc_us/wallet/img/mcpp_wllt_btn_chk_<?php echo Mage::getStoreConfig('masterpass/config/buttonsize'); ?>.png"/></a>
        </div>
        <?php if (Mage::getStoreConfig('masterpass/config/enabledlearnmore')): ?>
            <?php echo Mage::getStoreConfig('masterpass/config/learnmoremasterpasslink'); ?>
        <?php endif ?>
        <div style="margin: 25px 0 10px;">- OR -</div>

        <script type="text/javascript">
                            //<![CDATA[
                                    function pairWithMasterPass() {
                                    new Ajax.Request('<?php echo $this->getUrl() . 'masterpass/index/validatePk'; ?>',
                                    {
                                    method:'get',
                                            onSuccess: function(transport){
                                            var response = transport.responseText;
                                                    if (response != ''){
        <?php $data = $this->helper('masterpass')->getMerchantSettings(); ?>
                                            var token = "<?php print_r($this->helper('masterpass')->postShoppingCart()); ?>";
                                                    MasterPass.client.checkout({
                                                    "requestToken": token,
                                                            "callbackUrl": "<?php echo Mage::getUrl('', array('_secure' => true)) . "masterpass/index/callback"; ?>",
                                                            "pairingRequestToken": "<?php print_r($this->helper('masterpass')->postMerchantInitData()); ?>",
                                                            "requestExpressCheckout": <?php echo Mage::helper('masterpass')->requestExpressCheckout(); ?>,
                                                            "requestedDataTypes": "<?php echo Mage::helper('masterpass')->pairingDataTypes(); ?>",
                                                            "merchantCheckoutId": "<?php echo $data['checkout_id']; ?>",
                                                            "allowedCardTypes": "<?php print_r($this->helper('masterpass')->acceptedCards()); ?>",
                                                            "cancelCallback": "<?php echo $this->getUrl(); ?>",
                                                            "suppressShippingAddressEnable": "<?php echo $data['suppressShipping']; ?>",
                                                            "loyaltyEnabled": "<?php echo $data['loyaltyEnabled']; ?>",
                                                            "requestPairing": true,
                                                            "version": "<?php echo $data['version']; ?>"
                                                    });
                                            } else{
                                            location.reload();
                                            }
                                            } });
                                    }
                            //]]>
        </script>
    <?php } ?>
    <?php


 endif ?>
