<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<?php $data = $this->helper('masterpass')->getMerchantSettings(); ?>
<div id="standard-shipping-form" <?php if($data['suppressShipping']!='true' || $this->getAddress()->getFirstname()){ ?>style="display: none;" <?php } ?>>
    <form class="mp-shipping-form" name="mp-shipping-form" id="mp-shipping-form" method="post">
        <table>

            <tr>
                <td>
                    <label class="required" for="shipping:firstname">
                        <em>*</em>
                        First Name
                    </label>
                    <div class="input-box">
                        <input id="shipping:firstname" class="input-text required-entry mp-shipping-input" type="text" maxlength="255" title="First Name" value="<?php echo $this->getShipping()->getFirstname() ?>" name="shipping[firstname]">
                    </div>
                </td>
                <td>
                    <label class="required" for="shipping:lastname">
                        <em>*</em>
                        Last Name
                    </label>
                    <div class="input-box">
                        <input id="shipping:lastname" class="input-text required-entry mp-shipping-input" type="text" maxlength="255" title="Last Name" value="<?php echo $this->getShipping()->getLastname() ?>" name="shipping[lastname]">
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <label for="shipping:company">Company</label>
                    <div class="input-box">
                        <input id="shipping:company" class="input-text mp-shipping-input-wide" type="text" title="Company" value="" name="shipping[company]">
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <label class="required" for="shipping:street1">
                        <em>*</em>
                        Address
                    </label>
                    <div class="input-box">
                        <input id="shipping:street1" class="input-text required-entry shipping-address mp-shipping-input-wide" type="text" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" name="shipping[street][]" title="Street Address">
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="input-box">
                        <input id="shipping:street2" class="input-text shipping-address mp-shipping-input-wide" type="text" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(2)) ?>" name="shipping[street][]" title="Street Address 2">
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <label class="required" for="shipping:city">
                        <em>*</em>
                        City
                    </label>
                    <div class="input-box">
                        <input id="shipping:city" class="input-text required-entry mp-shipping-input-wide" type="text" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" name="shipping[city]" title="City">
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select mp-shipping-input-wide" style="display:none;">
                            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                            //<![CDATA[
                            $('shipping:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
                            //]]>
                        </script>
                        <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text mp-shipping-input-wide" style="display:none;" />
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <label class="required" for="shipping:postcode">
                        <em>*</em>
                        Zip/Postal Code
                    </label>
                    <div class="input-box">
                        <input id="shipping:postcode" class="input-text validate-zip-international required-entry mp-shipping-input-wide" type="text" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" name="shipping[postcode]" title="Zip/Postal Code">
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box" style="width: 264px !important;">
                        <?php echo $this->getCountryHtmlSelect('shipping') ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <label class="required" for="shipping:telephone">
                        <em>*</em>
                        Telephone
                    </label>
                    <div class="input-box">
                        <input id="shipping:telephone" class="input-text required-entry mp-shipping-input-wide" type="text" title="Telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" name="shipping[telephone]">
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <button id="masterpass-checkout" class="button mp-checkout-button" type="submit" title="Update Total" name="update" value="update">
                        <span>
                            <span>Update Shipping</span>
                        </span>
                    </button>
                </td>
            </tr>
        </table>
    </form>
</div>
<script type="text/javascript">
    //<![CDATA[
    document.getElementById('shipping:country_id').setAttribute("style", "width:264px !important;");
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');

    function updateShipping() {
        document.getElementById('standard-shipping-form').setAttribute("style", "display:block;");
    }

    var formId = 'mp-shipping-form';
    var myForm = new VarienForm(formId, true);
    //]]>
</script>