<?php

$totals = Mage::getSingleton('checkout/session')->getQuote()->getTotals(); //Total object
$subtotal = round($totals["subtotal"]->getValue()); //Subtotal value
?>

    
<?php if (!($_shippingRateGroups = $this->getShippingRates())): ?>
<div class="box-title">
                    <h3 class="mp-title"><?php echo $this->__("Shipping Method"); ?></h3>
                </div>
    <strong><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></strong>
<?php else: ?>
    <?php if (count($_shippingRateGroups) == '1' && Mage::getStoreConfig('onestepcheckout/general/hide_shipping_method')): ?>
    <div class="box">
                <div class="box-title">
                    <h3 class="mp-title"><?php echo $this->__("Shipping Method"); ?></h3>
                </div>
        <div id="required-shipping" class="validation-advice" style="display: none;">Please select a shipping method.</div>
            </div>
        <dl class="shipment-methods" style="display: none">
            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>

                <dd><?php echo $this->getCarrierName($code) ?></dd>
                <?php foreach ($_rates as $_rate): ?>
                    <dt style="margin-bottom: 5px;">
                    <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                    <?php else: ?>
                        <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" onclick="updateShippingMethod('<?php echo $_rate->getCode() ?>')"/>
                        <label for="s_method_<?php echo $_rate->getCode() ?>"><!--<b><?php echo $this->getCarrierName($code) ?>:</b>--> <?php echo $_rate->getMethodTitle() ?>
                            <strong>
                                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                <?php echo $_excl; ?>
                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                            </strong>
                        </label>
                    <?php endif ?>
                    </dt>

                <?php endforeach; ?>

            <?php endforeach; ?>
        </dl>
    <?php else: ?>
        <dl class="shipment-methods">
            <div class="box">
                <div class="box-title">
                    <h3 class="mp-title"><?php echo $this->__("Shipping Method"); ?></h3>
                </div>
                <div id="required-shipping" class="validation-advice" style="display: none;">Please select a shipping method.</div>
            </div>
            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                <dd><?php echo $this->getCarrierName($code) ?></dd>
                <?php foreach ($_rates as $_rate): ?>
                    <dt style="margin-bottom: 5px;">

                    <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                    <?php else: ?>
                        <input name="shipping_method" type="radio" class="validate-one-required-by-name" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if ($_rate->getCode() === $this->getAddressShippingMethod()) echo ' checked="checked"' ?> onclick="updateShippingMethod('<?php echo $_rate->getCode() ?>')"/>
                        <label for="s_method_<?php echo $_rate->getCode() ?>"><!--<b><?php echo $this->getCarrierName($code) ?>:</b>--> <?php echo $_rate->getMethodTitle() ?>
                            <strong>
                                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                                <?php echo $_excl; ?>
                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                            </strong>
                        </label>
                    <?php endif ?>
                    </dt>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
<?php endif; ?>
